// <auto-generated />
using System;
using EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramework.Entities.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("House")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Region")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("City");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("EntityFramework.Entities.AuctionLot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionLotItemID");

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("OrphanID");

                    b.HasKey("ID");

                    b.HasIndex("AuctionLotItemID");

                    b.HasIndex("OrphanID");

                    b.ToTable("AuctionLot");
                });

            modelBuilder.Entity("EntityFramework.Entities.BaseItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<float>("Price");

                    b.HasKey("ID");

                    b.ToTable("BaseItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseItem");
                });

            modelBuilder.Entity("EntityFramework.Entities.BaseItemType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("ParentID");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("BaseItemType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseItemType");
                });

            modelBuilder.Entity("EntityFramework.Entities.CharityMaker", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressID");

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("EmailID");

                    b.Property<bool>("IsDeleted");

                    b.Property<float>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("AddressID")
                        .IsUnique()
                        .HasFilter("[AddressID] IS NOT NULL");

                    b.ToTable("CharityMakers");
                });

            modelBuilder.Entity("EntityFramework.Entities.Donation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CharityMakerID");

                    b.Property<int?>("DonationItemID");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRequest");

                    b.Property<DateTime>("LastDateWhenStatusChanged");

                    b.Property<int?>("OrphanageID");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.HasIndex("CharityMakerID");

                    b.HasIndex("DonationItemID")
                        .IsUnique()
                        .HasFilter("[DonationItemID] IS NOT NULL");

                    b.HasIndex("OrphanageID");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("EntityFramework.Entities.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<float?>("MapCoordX");

                    b.Property<float?>("MapCoordY");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("EntityFramework.Entities.Orphan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<bool>("ChildInOrphanage");

                    b.Property<bool>("Confirmation");

                    b.Property<int>("EmailID");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("OrphanageID")
                        .IsRequired();

                    b.Property<float>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("OrphanageID");

                    b.ToTable("Orphans");
                });

            modelBuilder.Entity("EntityFramework.Entities.Orphanage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdressID");

                    b.Property<string>("Avatar");

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LocationID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<float>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("AdressID")
                        .IsUnique()
                        .HasFilter("[AdressID] IS NOT NULL");

                    b.HasIndex("LocationID");

                    b.ToTable("Orphanages");
                });

            modelBuilder.Entity("EntityFramework.Entities.Representative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("EmailID");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OrphanageID");

                    b.Property<float>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("OrphanageID");

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("EntityFramework.Entities.TypeBaseItem", b =>
                {
                    b.Property<int>("ItemID");

                    b.Property<int>("TypeID");

                    b.HasKey("ItemID", "TypeID");

                    b.HasIndex("TypeID");

                    b.ToTable("TypeBaseItems");
                });

            modelBuilder.Entity("EntityFramework.Entities.Volunteer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressID");

                    b.Property<string>("Avatar");

                    b.Property<DateTime>("Birthday");

                    b.Property<int>("EmailID");

                    b.Property<bool>("IsDeleted");

                    b.Property<float>("Rating");

                    b.HasKey("ID");

                    b.HasIndex("AddressID")
                        .IsUnique()
                        .HasFilter("[AddressID] IS NOT NULL");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("EntityFramework.Entities.AuctionLotItem", b =>
                {
                    b.HasBaseType("EntityFramework.Entities.BaseItem");

                    b.HasDiscriminator().HasValue("AuctionLotItem");
                });

            modelBuilder.Entity("EntityFramework.Entities.DonationItem", b =>
                {
                    b.HasBaseType("EntityFramework.Entities.BaseItem");

                    b.HasDiscriminator().HasValue("DonationItem");
                });

            modelBuilder.Entity("EntityFramework.Entities.AuctionLotItemType", b =>
                {
                    b.HasBaseType("EntityFramework.Entities.BaseItemType");

                    b.Property<int?>("ItemID");

                    b.HasIndex("ItemID");

                    b.HasDiscriminator().HasValue("AuctionLotItemType");
                });

            modelBuilder.Entity("EntityFramework.Entities.AuctionLot", b =>
                {
                    b.HasOne("EntityFramework.Entities.AuctionLotItem", "AuctionLotItem")
                        .WithMany()
                        .HasForeignKey("AuctionLotItemID");

                    b.HasOne("EntityFramework.Entities.Orphan", "Orphan")
                        .WithMany("AuctionLots")
                        .HasForeignKey("OrphanID");
                });

            modelBuilder.Entity("EntityFramework.Entities.BaseItemType", b =>
                {
                    b.HasOne("EntityFramework.Entities.BaseItemType", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("EntityFramework.Entities.CharityMaker", b =>
                {
                    b.HasOne("EntityFramework.Entities.Address", "Address")
                        .WithOne()
                        .HasForeignKey("EntityFramework.Entities.CharityMaker", "AddressID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("EntityFramework.Entities.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("CharityMakerID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Patronymic")
                                .IsRequired();

                            b1.Property<string>("Surname")
                                .IsRequired();

                            b1.HasKey("CharityMakerID");

                            b1.ToTable("CharityMakers");

                            b1.HasOne("EntityFramework.Entities.CharityMaker")
                                .WithOne("FullName")
                                .HasForeignKey("EntityFramework.Entities.FullName", "CharityMakerID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Donation", b =>
                {
                    b.HasOne("EntityFramework.Entities.CharityMaker", "CharityMaker")
                        .WithMany("Donations")
                        .HasForeignKey("CharityMakerID");

                    b.HasOne("EntityFramework.Entities.DonationItem", "DonationItem")
                        .WithOne()
                        .HasForeignKey("EntityFramework.Entities.Donation", "DonationItemID");

                    b.HasOne("EntityFramework.Entities.Orphanage", "Orphanage")
                        .WithMany("Donations")
                        .HasForeignKey("OrphanageID");
                });

            modelBuilder.Entity("EntityFramework.Entities.Orphan", b =>
                {
                    b.HasOne("EntityFramework.Entities.Orphanage", "Orphanage")
                        .WithMany("Orphans")
                        .HasForeignKey("OrphanageID");

                    b.OwnsOne("EntityFramework.Entities.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("OrphanID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Patronymic")
                                .IsRequired();

                            b1.Property<string>("Surname")
                                .IsRequired();

                            b1.HasKey("OrphanID");

                            b1.ToTable("Orphans");

                            b1.HasOne("EntityFramework.Entities.Orphan")
                                .WithOne("FullName")
                                .HasForeignKey("EntityFramework.Entities.FullName", "OrphanID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Orphanage", b =>
                {
                    b.HasOne("EntityFramework.Entities.Address", "Adress")
                        .WithOne()
                        .HasForeignKey("EntityFramework.Entities.Orphanage", "AdressID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EntityFramework.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");
                });

            modelBuilder.Entity("EntityFramework.Entities.Representative", b =>
                {
                    b.HasOne("EntityFramework.Entities.Orphanage", "Orphanage")
                        .WithMany("Representatives")
                        .HasForeignKey("OrphanageID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("EntityFramework.Entities.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("RepresentativeID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Patronymic")
                                .IsRequired();

                            b1.Property<string>("Surname")
                                .IsRequired();

                            b1.HasKey("RepresentativeID");

                            b1.ToTable("Representatives");

                            b1.HasOne("EntityFramework.Entities.Representative")
                                .WithOne("FullName")
                                .HasForeignKey("EntityFramework.Entities.FullName", "RepresentativeID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.TypeBaseItem", b =>
                {
                    b.HasOne("EntityFramework.Entities.BaseItem", "Item")
                        .WithMany("TypeBaseItem")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EntityFramework.Entities.BaseItemType", "Type")
                        .WithMany("TypeBaseItem")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityFramework.Entities.Volunteer", b =>
                {
                    b.HasOne("EntityFramework.Entities.Address", "Address")
                        .WithOne()
                        .HasForeignKey("EntityFramework.Entities.Volunteer", "AddressID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("EntityFramework.Entities.FullName", "FullName", b1 =>
                        {
                            b1.Property<int>("VolunteerID")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Patronymic")
                                .IsRequired();

                            b1.Property<string>("Surname")
                                .IsRequired();

                            b1.HasKey("VolunteerID");

                            b1.ToTable("Volunteers");

                            b1.HasOne("EntityFramework.Entities.Volunteer")
                                .WithOne("FullName")
                                .HasForeignKey("EntityFramework.Entities.FullName", "VolunteerID")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.AuctionLotItemType", b =>
                {
                    b.HasOne("EntityFramework.Entities.AuctionLotItem", "Item")
                        .WithMany("AuctionLotItemTypes")
                        .HasForeignKey("ItemID");
                });
#pragma warning restore 612, 618
        }
    }
}
